"""add owner_id

Revision ID: 14c02d093520
Revises: c4839f7b6724
Create Date: 2024-11-27 16:14:35.057442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14c02d093520'
down_revision: Union[str, None] = 'c4839f7b6724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('owner_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'products', 'users', ['owner_id'], ['id'])
    op.drop_column('products', 'owner')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('owner', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'owner_id')
    # ### end Alembic commands ###
