FROM python:3.11-slim

WORKDIR /app

# Копирование всех файлов в каталог /app
COPY . .

# Установка компилятора gcc и других необходимых зависимостей
RUN apt-get update
RUN apt-get install -y sqlite3

# Установка зависимостей из requirements.txt

RUN pip install aiogram==2.25.2

# Копирование файла bot.db в каталог /data
COPY bot.db /data/

# Запуск приложения
CMD ["python", "main.py"]